name: Build Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle wrapper (if missing)
        run: |
          if [ ! -f "./gradlew" ]; then
            gradle wrapper
          fi
          chmod +x ./gradlew
      - run: ./gradlew MyProvider:make --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: MyProvider-apk
          path: MyProvider/build/outputs/plugin/**/*.apk
