name: Build Plugins

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install Android SDK + accept licenses (diperlukan AGP)
      - uses: android-actions/setup-android@v3

      # Pakai Gradle tanpa wrapper
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build Cloudstream plugin
        run: gradle MyProvider:make --no-daemon

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyProvider-apk
          path: MyProvider/build/outputs/plugin/**/*.apk
